graph BT
    %% Node styles
    classDef table fill:#f96,stroke:#333,stroke-width:2px,color:#000;
    classDef stored_proc fill:#9cf,stroke:#333,stroke-width:2px ,color:#000;
    sp_get_customer_by_id --> customers
    sp_register_or_update_customer --> customers
    sp_transfer_funds --> customers
    sp_update_customer_email --> customers
    sp_create_order --> orders
    sp_get_customer_orders --> orders
    sp_get_order_details --> orders
    sp_get_customer_by_id --> sp_get_customer_full_details
    sp_get_customer_orders --> sp_get_customer_full_details
    sp_get_order_details --> order_items
    sp_get_order_details --> products
    class products,orders,order_items,customers table;
    class sp_update_customer_email,sp_register_or_update_customer,sp_transfer_funds,sp_get_customer_by_id,sp_get_customer_orders,sp_get_order_details,sp_create_order,sp_get_customer_full_details stored_proc;
